# Generated by Django 4.1.6 on 2023-04-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travelling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='contact',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='authentication',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='authentication',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
