# Generated by Django 4.1.6 on 2023-04-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travelling', '0002_alter_authentication_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('psw', models.CharField(max_length=255)),
                ('pswr', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Authentication',
        ),
    ]
